// SPDX-License-Identifier: see repository LICENSE
//
// =============================================================================
//  ForceEnchant - Target signatures for libminecraftpe.so (Android arm64-v8a)
// =============================================================================
//
//  WHY THIS FILE EXISTS
//  --------------------
//  The original ForceEnchant is a Windows DLL. Its byte-pattern signatures were
//  produced from `Minecraft.Windows.exe` (x86-64) and DO NOT and CANNOT match
//  the Android ARM64 binary `libminecraftpe.so`. Different CPU architecture,
//  different compiler, different instruction encoding => different bytes.
//
//  Therefore the constants below are resolved by *symbol name* via
//  pl::signature::resolveSignature(), which accepts either a mangled symbol
//  name or an ARM64 byte pattern. Resolving by mangled name is the most stable
//  approach across minor game updates when the symbol table is present.
//
//  VERIFICATION STATUS (read this before shipping)
//  -----------------------------------------------
//  The two symbol names below are INFERENCE / HYPOTHESIS, derived from the
//  Itanium C++ ABI mangling of the class/method names documented in the
//  upstream Windows project and cross-referenced against LeviLamina naming.
//  They are NOT verified against a specific libminecraftpe.so on this machine
//  (no binary / IDA available here).
//
//  YOU MUST verify (and if necessary replace) them for YOUR target version:
//
//   1. Open the target libminecraftpe.so (arm64-v8a) in IDA Pro (use the
//      IDA Pro MCP) or Ghidra.
//   2. canEnchant:
//        - Search strings for an enchantment-related anchor, or locate
//          `ItemEnchants::canEnchant`. Confirm the prototype:
//             EnchantResult* canEnchant(ItemEnchants* this,
//                                       EnchantResult* out,
//                                       EnchantmentInstance const& inst,
//                                       bool allowNonVanilla)
//        - Copy its exact mangled name from the symbol table (Names window),
//          or, if stripped, generate a unique ARM64 byte pattern from its
//          prologue and paste it below instead of the mangled name.
//   3. validRange:
//        - Search strings for "commands.enchant.invalidLevel" -> xref into
//          EnchantCommand::execute -> find the preceding range-check call
//          (CommandUtils/Command validRange). Confirm prototype:
//             bool validRange(int value, int low, int high, ...)
//        - Copy its mangled name (or a generated byte pattern) below.
//
//  The runtime guards in EnchantHooks.cpp log a warning and skip a hook whose
//  signature fails to resolve, so an out-of-date entry degrades safely instead
//  of crashing the game.
//
//  HOW TO USE A BYTE PATTERN INSTEAD OF A NAME
//  -------------------------------------------
//  resolveSignature() also accepts AArch64 byte patterns with wildcards, e.g.
//      "FF 83 01 D1 ?? ?? ?? A9 F4 4F 02 A9"
//  Just replace the string value below with the pattern you generate.
// =============================================================================
#pragma once

namespace fe::sig {

// Target module name (Android arm64-v8a Minecraft Bedrock binary).
inline constexpr const char* kModule = "libminecraftpe.so";

// ItemEnchants::canEnchant(EnchantResult*, EnchantmentInstance const&, bool)
// Itanium-mangled name (HYPOTHESIS - verify in IDA, see header note above).
inline constexpr const char* kCanEnchant =
    "_ZNK12ItemEnchants10canEnchantER13EnchantResultRK19EnchantmentInstanceb";

// Command range validation used by EnchantCommand::execute for the level arg.
// Itanium-mangled name (HYPOTHESIS - verify in IDA, see header note above).
// Bedrock exposes this as a templated helper; the int overload is targeted.
inline constexpr const char* kValidRange =
    "_ZN12CommandUtils10validRangeIiEEbT_S1_S1_PNSt6__ndk112basic_stringIcNS2_"
    "11char_traitsIcEENS2_9allocatorIcEEEE";

} // namespace fe::sig
